default_config:
lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/fluid-progressbar-card.js
      type: module

input_number:
  battery_level:
    name: Battery Level
    initial: 20
    min: 0
    max: 100
    step: .5
    icon: hass:battery


demo:

